require: rubocop-performance

AllCops:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'
    - 'config/**/*'
    - 'lib/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'Rakefile'
    - 'app/channels/**/*'

Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  Enabled: false
